In [2]:
import pandas as pd
import os 

LEAF_PATH = "/home/mountagha/projetIFT712"

def load_leaf_data(leaf_path=LEAF_PATH):
    csv_path = os.path.join(leaf_path, "train.csv")
    return pd.read_csv(csv_path)

In [5]:
leaf = load_leaf_data()
leaf.head()

id                species   margin1   margin2   margin3   margin4  \
0   1            Acer_Opalus  0.007812  0.023438  0.023438  0.003906   
1   2  Pterocarya_Stenoptera  0.005859  0.000000  0.031250  0.015625   
2   3   Quercus_Hartwissiana  0.005859  0.009766  0.019531  0.007812   
3   5        Tilia_Tomentosa  0.000000  0.003906  0.023438  0.005859   
4   6     Quercus_Variabilis  0.005859  0.003906  0.048828  0.009766   

    margin5   margin6   margin7  margin8    ...      texture55  texture56  \
0  0.011719  0.009766  0.027344      0.0    ...       0.007812   0.000000   
1  0.025391  0.001953  0.019531      0.0    ...       0.000977   0.000000   
2  0.003906  0.005859  0.068359      0.0    ...       0.154300   0.000000   
3  0.021484  0.019531  0.023438      0.0    ...       0.000000   0.000977   
4  0.013672  0.015625  0.005859      0.0    ...       0.096680   0.000000   

   texture57  texture58  texture59  texture60  texture61  texture62  \
0   0.002930   0.002930   0.035156        0.0        0.0   0.004883   
1   0.000000   0.000977   0.023438        0.0        0.0   0.000977   
2   0.005859   0.000977   0.007812        0.0        0.0   0.000000   
3   0.000000   0.000000   0.020508        0.0        0.0   0.017578   
4   0.021484   0.000000   0.000000        0.0        0.0   0.000000   

   texture63  texture64  
0   0.000000   0.025391  
1   0.039062   0.022461  
2   0.020508   0.002930  
3   0.000000   0.047852  
4   0.000000   0.031250  

[5 rows x 194 columns]

In [5]:
leaf.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 990 entries, 0 to 989
Data columns (total 194 columns):
id           int64
species      object
margin1      float64
margin2      float64
margin3      float64
margin4      float64
margin5      float64
margin6      float64
margin7      float64
margin8      float64
margin9      float64
margin10     float64
margin11     float64
margin12     float64
margin13     float64
margin14     float64
margin15     float64
margin16     float64
margin17     float64
margin18     float64
margin19     float64
margin20     float64
margin21     float64
margin22     float64
margin23     float64
margin24     float64
margin25     float64
margin26     float64
margin27     float64
margin28     float64
margin29     float64
margin30     float64
margin31     float64
margin32     float64
margin33     float64
margin34     float64
margin35     float64
margin36     float64
margin37     float64
margin38     float64
margin39     float64
margin40     float64
margin41     fl

In [6]:
leaf["species"].value_counts()

Alnus_Maximowiczii             10
Quercus_Semecarpifolia         10
Eucalyptus_Glaucescens         10
Rhododendron_x_Russellianum    10
Cytisus_Battandieri            10
Lithocarpus_Edulis             10
Quercus_Rubra                  10
Ilex_Cornuta                   10
Betula_Austrosinensis          10
Alnus_Cordata                  10
Quercus_Phillyraeoides         10
Cercis_Siliquastrum            10
Quercus_Crassipes              10
Quercus_Texana                 10
Quercus_x_Turneri              10
Ulmus_Bergmanniana             10
Celtis_Koraiensis              10
Quercus_Imbricaria             10
Olea_Europaea                  10
Quercus_Suber                  10
Acer_Palmatum                  10
Cotinus_Coggygria              10
Prunus_X_Shmittii              10
Populus_Adenopoda              10
Liriodendron_Tulipifera        10
Callicarpa_Bodinieri           10
Cornus_Chinensis               10
Prunus_Avium                   10
Eucalyptus_Neglecta            10
Sorbus_Aria   

In [7]:
leaf.describe()

id     margin1     margin2     margin3     margin4  \
count   990.000000  990.000000  990.000000  990.000000  990.000000   
mean    799.595960    0.017412    0.028539    0.031988    0.023280   
std     452.477568    0.019739    0.038855    0.025847    0.028411   
min       1.000000    0.000000    0.000000    0.000000    0.000000   
25%     415.250000    0.001953    0.001953    0.013672    0.005859   
50%     802.500000    0.009766    0.011719    0.025391    0.013672   
75%    1195.500000    0.025391    0.041016    0.044922    0.029297   
max    1584.000000    0.087891    0.205080    0.156250    0.169920   

          margin5     margin6     margin7     margin8     margin9     ...      \
count  990.000000  990.000000  990.000000  990.000000  990.000000     ...       
mean     0.014264    0.038579    0.019202    0.001083    0.007167     ...       
std      0.018390    0.052030    0.017511    0.002743    0.008933     ...       
min      0.000000    0.000000    0.000000    0.000000    0.000000     ...       
25%      0.001953    0.000000    0.005859    0.000000    0.001953     ...       
50%      0.007812    0.015625    0.015625    0.000000    0.005859     ...       
75%      0.017578    0.056153    0.029297    0.000000    0.007812     ...       
max      0.111330    0.310550    0.091797    0.031250    0.076172     ...       

        texture55   texture56   texture57   texture58   texture59   texture60  \
count  990.000000  990.000000  990.000000  990.000000  990.000000  990.000000   
mean     0.036501    0.005024    0.015944    0.011586    0.016108    0.014017   
std      0.063403    0.019321    0.023214    0.025040    0.015335    0.060151   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    0.000977    0.000000    0.004883    0.000000   
50%      0.004883    0.000000    0.005859    0.000977    0.012695    0.000000   
75%      0.043701    0.000000    0.022217    0.009766    0.021484    0.000000   
max      0.429690    0.202150    0.172850    0.200200    0.106450    0.578130   

        texture61   texture62   texture63   texture64  
count  990.000000  990.000000  990.000000  990.000000  
mean     0.002688    0.020291    0.008989    0.019420  
std      0.011415    0.039040    0.013791    0.022768  
min      0.000000    0.000000    0.000000    0.000000  
25%      0.000000    0.000000    0.000000    0.000977  
50%      0.000000    0.003906    0.002930    0.011719  
75%      0.000000    0.023438    0.012695    0.029297  
max      0.151370    0.375980    0.086914    0.141600  

[8 rows x 193 columns]

In [10]:
%matplotlib inline
import matplotlib.pyplot as plt
leaf.hist(bins=10, figsize=(20,15))

array([[<matplotlib.axes._subplots.AxesSubplot object at 0x7fe17a61d208>,
      dtype=object)

In [7]:
from sklearn.preprocessing import Imputer
# Ceci est pour gérer les données manquantes dans notre dataset
# imputer calcul dans notre cas ici la mediane pour chaque feature (numerique) afin que ce dernier serve
# de remplacement aux données manquantes
imputer = Imputer(strategy="median")
data_leaf = leaf.drop("id", axis=1)
data_leaf = data_leaf.drop("species", axis=1)
imputer.fit(data_leaf)
imputer.statistics_[:10]
data_leaf.median().values[:10]

array([0.009766, 0.011719, 0.025391, 0.013672, 0.007812, 0.015625,
       0.015625, 0.      , 0.005859, 0.015625])

In [9]:
#Imputer stoque les valeurs calculés dans le tableau statistics_
imputer.statistics_[:10]

array([0.009766, 0.011719, 0.025391, 0.013672, 0.007812, 0.015625,
       0.015625, 0.      , 0.005859, 0.015625])

In [14]:
# Pour vérifier que imputer calcule bien les medianes
import numpy
data_leaf.median().values[:10]

array([0.009766, 0.011719, 0.025391, 0.013672, 0.007812, 0.015625,
       0.015625, 0.      , 0.005859, 0.015625])

In [15]:
# une fois qu'on a fait le calcul on peut appliquer les transformations aux données(ie filling missing datas) 
X_train = imputer.transform(data_leaf)

In [18]:
# ceci permet de remettre les données dans le format initial(comme après avoir importé pandas)
leaf_cleaned = pd.DataFrame(X_train, columns=data_leaf.columns)

In [19]:
# Les algorithmes de machine learning sont connus pour être plus performants quand ils travaillent avec des données 
# numériques. Convertissons donc nos données textes sous forme de données numériques. Pour cela scikit learn fournit 
# un transformateur pour cette tâche appelé LabelEncoder.
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
leaf_species = leaf["species"]
leaf_species_encoded = encoder.fit_transform(leaf_species)
leaf_species_encoded

array([ 3, 49, 65, 94, 84, 40, 54, 78, 53, 89, 98, 16, 74, 50, 58, 31, 43,
        4, 75, 44, 83, 84, 13, 66, 15,  6, 73, 22, 73, 31, 36, 27, 94, 88,
       12, 28, 21, 25, 20, 60, 84, 65, 69, 58, 23, 76, 18, 52, 54,  9, 48,
       47, 64, 81, 83, 36, 58, 21, 81, 20, 62, 88, 34, 92, 79, 82, 20, 32,
        4, 84, 36, 35, 72, 60, 71, 72, 52, 50, 54, 11, 51, 18, 47,  5,  8,
       37, 97, 20, 33,  1, 59,  1, 56,  1,  9, 57, 20, 79, 29, 16, 32, 54,
       93, 10, 46, 59, 84, 76, 15, 10, 15,  0, 69,  4, 51, 51, 94, 36, 39,
       62,  2, 24, 26, 35, 25, 87,  0, 55, 34, 38,  1, 45,  7, 93, 56, 38,
       21, 51, 75, 81, 74, 33, 20, 37,  9, 40, 60, 31, 83, 50, 71, 67, 30,
       66,  1, 43, 61, 23, 65, 84, 87, 46, 57, 16,  2, 28, 12, 96, 44, 76,
       29, 75, 41, 87, 67, 61, 30,  5, 12, 62,  3, 83, 81,  6, 85,  4, 37,
       57, 84, 39, 71, 61,  6, 76, 14, 31, 98, 40, 17, 51, 16, 42, 63, 86,
       37, 69, 86, 71, 80, 78, 14, 35, 25,  5, 39,  8,  9, 26, 44, 60, 13,
       14, 77, 13, 80, 87

In [20]:
print(encoder.classes_[:10])

['Acer_Capillipes' 'Acer_Circinatum' 'Acer_Mono' 'Acer_Opalus'
 'Acer_Palmatum' 'Acer_Pictum' 'Acer_Platanoids' 'Acer_Rubrum'
 'Acer_Rufinerve' 'Acer_Saccharinum']


In [21]:
# le downside de cette technique notre model pourrait penser que deux catégories ayant des nombres "proches" 
# sont similaires ce qui n'est pas le cas. une solution à ce problème est d'utiliser le one-hot-encoding sur les données 
# déjà labelisés. le fit_transorm de OneHotEncoder attend un 2D alors que les données renvoyés par LabelEncoder 1D
# il faut donc les reshape
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
leaf_species_onehot = encoder.fit_transform(leaf_species_encoded.reshape(-1,1))
leaf_species_onehot

<990x99 sparse matrix of type '<class 'numpy.float64'>'
	with 990 stored elements in Compressed Sparse Row format>

In [24]:
#on aurait pu utiliser LabelBinarizer = LabelEncoder + OneHotEncoder
leaf_cleaned.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 990 entries, 0 to 989
Data columns (total 193 columns):
margin1      float64
margin2      float64
margin3      float64
margin4      float64
margin5      float64
margin6      float64
margin7      float64
margin8      float64
margin9      float64
margin10     float64
margin11     float64
margin12     float64
margin13     float64
margin14     float64
margin15     float64
margin16     float64
margin17     float64
margin18     float64
margin19     float64
margin20     float64
margin21     float64
margin22     float64
margin23     float64
margin24     float64
margin25     float64
margin26     float64
margin27     float64
margin28     float64
margin29     float64
margin30     float64
margin31     float64
margin32     float64
margin33     float64
margin34     float64
margin35     float64
margin36     float64
margin37     float64
margin38     float64
margin39     float64
margin40     float64
margin41     float64
margin42     float64
margin43    

In [23]:
leaf_cleaned["species"] = leaf_species_onehot